### ISSUE TITLE
[suggestion] Anchored ender chest cart

### ISSUE THREAD

**Issue by CrazyNagaraj** [buttilda/IronChestMinecarts#5]
Please add Anchored ender chest cart, if Ganys' End is loaded. I Hoping, I have no need to explain how much it is useful. Thanks in advance... :)

EDIT: Sorry, Wrong project. (What I'm thinking, anchored ender chest is not from iron chests mod). Anyway, Please implement it in Gany's End.

**Comment by buttilda** [comment]
Yeah would be a good addition:3
I'll move this issue to the Gany's End page otherwise I'll forget about it XD
