### ISSUE TITLE
Item Loader/Unloader does not recognise carts

### ISSUE THREAD

**Issue by cloakable** [buttilda/IronChestMinecarts#6]
When you put a minecart from this mod in the filter, the cart is not stopped by the loader; apparently a mod needs to use the Railcraft API to get that to work.

Feature request I guess? It's the one thing stopping me being able to run a diamond chest cargo train :)

**Comment by CovertJaguar** [comment]
See https://github.com/CovertJaguar/Railcraft/issues/607

As stated there, I'm not sure what's going on, but the only API that the Loaders care about it IInventory.

**Comment by CovertJaguar** [comment]
Ah it appears to be because you don't implement EntityMinecart.getCartItem().

**Comment by buttilda** [comment]
Easy fix!
Thanks for the report.
